modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="twistermill"
version="${mod_version}"
displayName="Create Twistermill"
logoFile="icon.png"
authors="proventure"
description='''Compatibility bridge between Sable and Create’s kinetic system for Weather2 or ProtoManly’s Weather'''

[[mixins]]
config="twistermill.mixins.json"

[[dependencies.twistermill]]
modId="neoforge"
type="required"
versionRange="[21.1.229,)"
ordering="NONE"
side="BOTH"

[[dependencies.twistermill]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.twistermill]]
modId="create"
type="required"
versionRange="[6.0.10]"
ordering="NONE"
side="BOTH"

[[dependencies.twistermill]]
modId="sable"
type="required"
versionRange="[2.0.3,3.0.0)"
ordering="NONE"
side="BOTH"

[[dependencies.twistermill]]
modId="weather2"
type="optional"
versionRange="[1.21.0-2.8.7,)"
ordering="AFTER"
side="BOTH"

[[dependencies.twistermill]]
modId="coroutil"
type="optional"
versionRange="[1.3.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.twistermill]]
modId="pmweather"
type="optional"
versionRange="[0.16.4,)"
ordering="AFTER"
side="BOTH"

[[dependencies.twistermill]]
modId="sodium"
type="required"
versionRange="[0.8.12+mc1.21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.twistermill]]
modId="framedblocks"
type="optional"
versionRange="[10.6.0,)"
ordering="AFTER"
side="BOTH"

